---
# tasks file for nginx
- name: Fail if required variables are not defined
  fail:
    msg: "Variable '{{ item }}' is not defined"
  when: item is undefined
  with_items:
    - "{{ project_name }}"
    - "{{ docker_image }}"
    - "{{ service_name }}"

- name: Creates persistent volume
  file:
    path: "{{ persistent_volume }}"
    state: directory
  when: persistent_volume is defined

- name: Create nginx conf file
  template:
    src: templates/default.conf.j2
    dest: "{{persistent_volume}}/default.conf"
    owner: root
    group: root
    mode: 0644

- name: Configure docker service
  docker_container:
    state: started
    name: "{{ project_name }}_{{ service_name }}"
    image: "{{ docker_image }}"
    ports:
      - "80:80"
    volumes:
      - "{{ persistent_volume }}/default.conf:/etc/nginx/conf.d/default.conf:ro"
  register: docker_create_output

- name: Create docker systemd file
  template:
    src: templates/docker.service.j2
    dest: "/etc/systemd/system/docker_{{ project_name }}_{{ service_name }}.service"
    owner: root
    group: root
    mode: 0644

- name: "start and enable docker {{ service_name }} service"
  service:
    name: "docker_{{ project_name }}_{{ service_name }}.service"
    enabled: yes
    state: started
